### ISSUE TITLE
View passed testcases and show log messages in html report?

### ISSUE THREAD

**Issue by bvidovic1** [oldani/HtmlTestRunner#27]
* HtmlTestRunner version: 1.1.2
* Python version: Python 2.7.13
* Operating System: Red Hat Enterprise Linux Server 7.4

### Description

1) I was wondering if it is possible to view PASSED testcases? Currently there is only option to check ERROR and FAILED ones.

2) Is there a way to log in HTML report? I was trying to use logger but it is visible only in console output, not html report output.

Thanks in advance.

/Bojan

**Comment by oldani** [comment]
1. Hi, it's actually not possible, when I create the package it was not necessary to see a message of a test passed; I wonder what do you want to see?

2. There's no way to this right now, but we can take a look to implement, could you describe better what you want to achieve with this?

**Comment by adolfo-rt** [comment]
> ...could you describe better what you want to achieve with this?

My 2 cents: When generating reports, it's sometimes useful to leave an explicit record of what has been exercised by the tests, and not only the errors. We have a usecase where we want to compare generated data against ground truth values. Since we don't necessarily compare all reported data, it's convenient to see at a glance what things are being compared, even when the comparison is successful.

The [HTMLTestRunner](https://github.com/tungwaiyip/HTMLTestRunner) package present results in a compact format that doesn't impose a lot of clutter on the eye:
* Single HTML report for all testcases. Currently tracked in #6 for this project. This is a dealbreaker for us.
* Testcases with errors show up expanded, detailing each failed test.
* Testcases without errors show up collapsed, but one can expand them on demand to inspect the details.

![image](https://user-images.githubusercontent.com/1128028/37510189-a38892ca-28fa-11e8-998d-837006053682.png)

Maybe this is out of the scope of `HtmlTestRunner`. I don't want to impose a personal preference, but rather share the features particular users have.

**Comment by oldani** [comment]
I'm working on #6, also will take a look at #28

Regarding:
> it's convenient to see at a glance what things are being compared, even when the comparison is successful

How do you do this right now or how would you like to do this?logging?

And for how it looks, one #6 is finished you can create your own template and display the results a wished, don't have to be exactly with the one provided, you can make it look completely different.

**Comment by liushilive** [comment]
如果你愿意使用Python 3的情况下，可以使用我的项目：https://github.com/liushilive/HTMLReport

预览：https://liushilive.github.io/HTMLReport/tests/report/test.html

If you are willing to use Python 3, you can use my project：https://github.com/liushilive/HTMLReport

preview：https://liushilive.github.io/HTMLReport/tests/report/test.html

**Comment by MukhtarSheikh** [comment]
@liushilive the report you shared is not accessible. Can you please check?

@oldani i also vote for this feature. It's good to have this feature for comparison purposes. We might hit by a case where our test was passing earlier and failing afterwards and we want to check what was executing earlier and what's going wrong now. There maybe other cases as well.
This package definitely have better view than the unittestreport. Enhancing this with better logging would help in lots of cases. Thanks.

**Comment by oldani** [comment]
Hey @MukhtarSheikh 

I'm a busy this days but a 2.0 release is on the way, but I still ask, how do you want this to work guys? Give me an example.

**Comment by liushilive** [comment]
@oldani  https://liushilive.github.io/report/report/index.html#en

**Comment by changdapu** [comment]
> 如果你愿意使用Python 3的情况下，可以使用我的项目：[https](https://github.com/liushilive/HTMLReport)：[//github.com/liushilive/HTMLReport](https://github.com/liushilive/HTMLReport)
> 
> 预览：[https](https://liushilive.github.io/report/report/index.html#en)：[//liushilive.github.io/report/report/index.html#en](https://liushilive.github.io/report/report/index.html#en)
> 
> 如果您愿意使用Python 3，您可以使用我的项目：[https](https://github.com/liushilive/HTMLReport)：[//github.com/liushilive/HTMLReport](https://github.com/liushilive/HTMLReport)
> 
> 预览：[https](https://liushilive.github.io/report/report/index.html#en)：[//liushilive.github.io/report/report/index.html#en](https://liushilive.github.io/report/report/index.html#en)

你的报告非常好，可以这个 项目地址怎么打不开？ https://github.com/liushilive/HTMLReport

**Comment by changdapu** [comment]
> 如果你愿意使用Python 3的情况下，可以使用我的项目：https://github.com/liushilive/HTMLReport
> 
> 预览：https://liushilive.github.io/report/report/index.html#en
> 
> If you are willing to use Python 3, you can use my project：https://github.com/liushilive/HTMLReport
> 
> preview：https://liushilive.github.io/report/report/index.html#en

https://pypi.org/project/HTMLReport/

非常好！

**Comment by liushilive** [comment]
由于我的项目是给学生练习使用的，所以请使用 1.5.1 的版本。

Since my project is for students to practice using, please use version 1.5.1.

```
pip install htmlreport==1.5.1
```

**Comment by oldani** [comment]
This was implemented by @JamesMTSloan. Released under version `1.2`
