### ISSUE TITLE
combining results to one html report

### ISSUE THREAD

**Issue by yitzchakl** [oldani/HtmlTestRunner#6]
* HtmlTestRunner version: 1.0.3
* Python version: 2.7.12
* Operating System: Ubuntu 16.04 LTS

### Description

Hi,
How is it possible to combine several test classes to create one html report?
i'm using unittest TestLoader to discover all test suites in my package:

    runner = HtmlTestRunner.HTMLTestRunner(output='reports')
    test_suite = unittest.TestLoader().discover('./', '*_test.py', '.')
    runner.run(test_suite)

Thanks,
Yitzchak.

**Comment by oldani** [comment]
Hi Yitzchak,

Sorry but right now it will create one report per TestCase on your suite, i'm goint to put this for next releases:)

**Comment by debugtalk** [comment]
@oldani Can I implement this feature?

**Comment by oldani** [comment]
@debugtalk for sure you can

**Comment by davesave** [comment]
still waiting for this :)
also, I would really like to see an overview/summary page with links to all unit tests sub pages.

**Comment by oldani** [comment]
Got it, I will start getting my hands on this next week, sorry I was full busy these past months

**Comment by oldani** [comment]
I already started working on this, is getting a bit tricky to implement this and maintain the old API, so it will take me a bit longer.

**Comment by adolfo-rt** [comment]
Thanks for taking the time to look into this. Much appreciated.

**Comment by jprince14** [comment]
If you want to preserve the old api and keep this feature one thing you could do is have a class variable in HTMLTestRunner class which is a boolean that defaults to using the original method of one html file per unittest class but could be set to combine all results in a single file and use a different template. I started looking into this but I know jinja2 so I couldn't make a new template. Rather than calling generate_reports you could make a new function that passes the results for every test into the new template.

**Comment by oldani** [comment]
Version 1.2 has been released with all these wonderful changes:)

Sorry everybody for the delay here. This is all thanks to @JamesMTSloan

**Comment by JoseMarulanda** [comment]
hi how it is resolved still looking for this answer

**Comment by sheva** [comment]
runner = HTMLTestRunner(output='blablabla', report_name='Test_Results', combine_reports=True)
test_suite = unittest.TestLoader().discover('./', 'test_*.py', '.')
runner.run(test_suite)
